name: Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Set variables
      id: vars
      run: |
        echo "::set-output name=tag::vandrijevik/kubekit:latest"

    - uses: actions/checkout@v1

    - name: Build Docker image
      run: docker build . --tag ${{steps.vars.outputs.tag}}

    - name: Login to Docker registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push image to Docker registry
      run: docker push ${{steps.vars.outputs.tag}}
